runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://admin:pass@ds157639.mlab.com:57639/heroku_fggv6w17
  APP_ID: myAppId
  MASTER_KEY: myMasterKey
  SERVER_URL: http://uers-test.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
